### ISSUE TITLE
作者 你的插件很棒,我想说可以留个联系方式嘛

### ISSUE THREAD

**Issue by KiritoLifeF** [nincenet/EpHelper-Release#2]
我自己弄了个网站 收集各种很棒的应用,看到作者做得这个真的很棒,想让您发布到我的网站上,如果有意向的话.QQ3390201260.
https://chengame.cn/bbs

**Comment by nincenet** [comment]
我看你已经挂到网站上去了，但是记得引用软件的时候，要把作者和原始地址加上。
